"""empty message

Revision ID: 14d72a732c98
Revises: 24222eee586e
Create Date: 2024-01-04 18:14:00.332896

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '14d72a732c98'
down_revision = '24222eee586e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('eventTime',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Text(),
               nullable=False)
        batch_op.drop_index('ix_events_created')

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_index('ix_posts_created')
        batch_op.create_index(batch_op.f('ix_posts_created'), ['created'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_posts_created'))
        batch_op.create_index('ix_posts_created', ['created'], unique=False)

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index('ix_events_created', ['created'], unique=False)
        batch_op.alter_column('eventTime',
               existing_type=sa.Text(),
               type_=postgresql.TIMESTAMP(),
               nullable=True)

    # ### end Alembic commands ###
