"""empty message

Revision ID: 42cdeff0fe37
Revises: f823bb0dbceb
Create Date: 2024-01-09 13:28:42.514825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42cdeff0fe37'
down_revision = 'f823bb0dbceb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_comments_user_id_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_comments_user_id_users'), 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('eventTime',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=False)

    with op.batch_alter_table('post_comments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_post_comments_comment_id_comments', type_='foreignkey')
        batch_op.drop_constraint('fk_post_comments_post_id_posts', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_post_comments_post_id_posts'), 'posts', ['post_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_post_comments_comment_id_comments'), 'comments', ['comment_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_index('ix_posts_created')
        batch_op.create_index(batch_op.f('ix_posts_created'), ['created'], unique=False)
        batch_op.drop_constraint('fk_posts_user_id_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_posts_user_id_users'), 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_posts_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_posts_user_id_users', 'users', ['user_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_posts_created'))
        batch_op.create_index('ix_posts_created', ['created'], unique=False)

    with op.batch_alter_table('post_comments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_post_comments_comment_id_comments'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_post_comments_post_id_posts'), type_='foreignkey')
        batch_op.create_foreign_key('fk_post_comments_post_id_posts', 'posts', ['post_id'], ['id'])
        batch_op.create_foreign_key('fk_post_comments_comment_id_comments', 'comments', ['comment_id'], ['id'])

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('eventTime',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=False)

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_comments_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_comments_user_id_users', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
