"""empty message

Revision ID: 83a6b4e90013
Revises: 3282ad46ceb5
Create Date: 2024-01-25 17:28:03.557493

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '83a6b4e90013'
down_revision = '3282ad46ceb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   
    pass


def downgrade():
    pass