"""empty message

Revision ID: f6c2c28e37e4
Revises: 42cdeff0fe37
Create Date: 2024-01-09 13:38:43.431986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6c2c28e37e4'
down_revision = '42cdeff0fe37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_comments')
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_id', sa.UUID(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_comments_post_id_posts'), 'posts', ['post_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_index('ix_posts_created')
        batch_op.create_index(batch_op.f('ix_posts_created'), ['created'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_posts_created'))
        batch_op.create_index('ix_posts_created', ['created'], unique=False)

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_comments_post_id_posts'), type_='foreignkey')
        batch_op.drop_column('post_id')

    op.create_table('post_comments',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('post_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('comment_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], name='fk_post_comments_comment_id_comments', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name='fk_post_comments_post_id_posts', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='post_comments_pkey')
    )
    # ### end Alembic commands ###
